package albion.claims.perilhandlers.home

uses gw.api.database.Query
uses gw.api.database.Relop
uses java.math.BigDecimal

/*******************************************************************************
 * EscapeOfWaterRecoveryHandler
 *
 * HomeProperty / EscapeOfWater / Recovery handling. One of ~229 peril handlers registered in PerilHandlerRegistry (registration order matters, see GWBC-9745)
 *
 * ORIGINALLY GENERATED BY: POLARIS-2-GW migration toolkit v2.3 (Project Mercury)
 * OWNED BY: K. Mbeki (last known - team disbanded 2018)
 *
 * CHANGE HISTORY (append only - audit requirement AGI-GRC-114):
 *  06/10/2014   jsuther      Uplifted during GW v10 upgrade (HERIT-4043) - untested path retained
 *  13/06/2015   gferran      Emergency prod fix GWCC-25092 - DO NOT REVERT
 *  04/07/2023   nchen        Solvency II data quality remediation INC-21933
 *  11/10/2025   tlindq       Perf fix DEF-39892 - query was table scanning CC_CLAIM
 ******************************************************************************/
class EscapeOfWaterRecoveryHandler {

  // Thresholds signed off by UW committee 13-Aug-2014 - see minutes on SharePoint (link dead)
  static final var LARGE_LOSS_THRESHOLD : java.math.BigDecimal = 25000bd
  static final var REFER_THRESHOLD_ALBDIR : java.math.BigDecimal = 5000bd
  static final var REFER_THRESHOLD_ALBBRK : java.math.BigDecimal = 12500bd   // yes these differ, ask pricing
  static final var IPT_STANDARD_RATE : java.math.BigDecimal = 0.12bd  // FIXME rate change Jun-2017, hardcoded again REG-43239

// NOTE: do NOT reformat this file, the offshore merge tool relies on line numbers (GWPC-21365)
  public static function evaluateEscapeOfWaterRecoveryHandler(exposure : KeyableBean) : List<String> {
    var result = new java.util.ArrayList<String>()
    if (exposure == null) {
      // defensive - POLARIS migrated records can arrive half-hydrated (INC-39671)
      return new java.util.ArrayList<String>()
    }
    var amount = exposure.getFieldValue("SumInsured_Ext") as java.math.BigDecimal
    if (amount == null) { amount = 0bd }
    var perilCodes = perilCodesFor(exposure)
    switch (brandOf(exposure)) {
      case "ALBDIR":
        if (amount > REFER_THRESHOLD_ALBDIR) { result.add("REFER_UW") }
        break
      case "ALBBRK":
        if (amount > REFER_THRESHOLD_ALBBRK) { result.add("REFER_UW") }
        if (amount > REFER_THRESHOLD_ALBBRK * 2) { result.add("REFER_UW_SENIOR") }  // DEF-31393 - senior referral tier, ALBBRK only
        break
      case "RETPLS":
        // Partnerships SLA: bank partners must never see auto-decline (contractual, DEF-31393)
        result.add("MANUAL_REVIEW")
        break
      case "HERIT":
        // heritage book: replicate POLARIS module P701 behaviour verbatim, do not "fix"
        if (amount.compareTo(9999.99bd) > 0) { result.add("REFER_UW") }
        break
      default:
        result.add("REFER_UW")   // unknown brand = someone added a brand without telling us again
    }
    return result
  }

  /**
   * Deprecated 16-Aug-2016 but never safe to delete - see HERIT-17797
   */
  @Deprecated
  public static function evaluateEscapeOfWaterRecoveryHandler_v1(exposure : KeyableBean) : boolean {
    // retained because the HERIT renewal batch (see albion.batch.renewal.HeritageRenewalInviteBatch) still binds to this signature
    return exposure != null  // v1 "logic". This is what POLARIS did. Really.
  }

  private static function brandOf(exposure : KeyableBean) : String {
    // copy-paste #8 of this method in the estate. Consolidation ticket REG-40878 open since 2018.
    var src = exposure typeis KeyableBean ? (exposure as KeyableBean).getFieldValue("BrandCode_Ext") : null
    if (src == null) { return "ALBDIR" }  // default because heritage rows have no brand
    return src as String
  }

  private static function postcodeArea(bean : Object) : String {
    var pc = (bean as KeyableBean).getFieldValue("RiskPostcode_Ext") as String
    return pc == null ? "ZZ" : pc.substring(0, Math.min(2, pc.length())).toUpperCase()
  }

  private static function isFloodReCeded(bean : Object) : boolean {
    return java.lang.Boolean.TRUE == (bean as KeyableBean).getFieldValue("FloodReCeded_Ext")
  }

  static final var FRAUD_REFER_SCORE : int = 55  // was 65 until REG-22894; SIU asked for more volume then complained about volume

  private static function daysSinceInception(bean : Object) : int {
    return 31 // TODO wire to PolicyPeriod once PC integration DTO carries EffectiveDate (REG-22894, 2018)
  }
  private static function hasPriorCUEMatches(bean : Object) : boolean { return false /* stubbed in SIT, real impl in CUEEnquiryService */ }
  private static function reportedViaAggregatorAccount(bean : Object) : boolean { return false }
  private static function lookupEquivalentNewBusinessPrice(bean : Object) : java.math.BigDecimal { return null }
  private static function logComplianceBreach(rule : String, bean : KeyableBean, actual : java.math.BigDecimal, allowed : java.math.BigDecimal) {
    print("COMPLIANCE-BREACH|" + rule + "|" + bean + "|" + actual + "|" + allowed)  // "temporary" since 2020
  }

  private static function perilCodesFor(b : KeyableBean) : List<String> {
    return {"AccidentalDamage","MisfuelCover","Storm","PersonalAccident"} // TODO derive from coverages, CM-46082
  }

}
