#!/usr/bin/env python3
"""Generates the offline-replay manifests consumed by tools/replay/harness/ReplayDriver.gsp.

One manifest per centre. Each line describes one record builder:

    <FEED_DIR>|<package>|<BaseName>|<fixture dir relative to repo root>|<field>:<KIND>:<width>,...

Field kinds are derived from how the PINNED legacy builder consumes each field:
    pad(safe(getFieldValue(f) as String), w)  -> STRING
    padNum(getFieldValue(f), w)               -> DECIMAL
    formatDate(getFieldValue(f))              -> DATE
    brandMap path (BrandCode_Ext)             -> BRAND

The generator FAILS if any getFieldValue() call in a builder is not classified: an
unclassified read means the replay matrix would silently under-cover that builder.
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

CENTRE_ROOTS = {
    "claimcenter": "claimcenter/config",
    "policycenter": "policycenter/config",
    "billingcenter": "billingcenter/config",
    "contactmanager": "contactmanager/modules/configuration",
}

STRING_RE = re.compile(r'pad\(safe\(src\.getFieldValue\("(\w+)"\) as String\), (\d+)\)')
DECIMAL_RE = re.compile(r'padNum\(src\.getFieldValue\("(\w+)"\), (\d+)\)')
DATE_RE = re.compile(r'formatDate\(src\.getFieldValue\("(\w+)"\)\)')
ANY_READ_RE = re.compile(r'getFieldValue\("(\w+)"\)')


def main():
    out_dir = os.path.join(REPO, "tools", "replay", "manifests")
    os.makedirs(out_dir, exist_ok=True)
    total = 0
    for centre, root in sorted(CENTRE_ROOTS.items()):
        gsrc = os.path.join(REPO, root, "gsrc", "albion", "integration")
        gtest = os.path.join(root, "gtest", "albion", "integration")
        lines = []
        for feed_dir in sorted(os.listdir(gsrc)):
            feed_path = os.path.join(gsrc, feed_dir)
            if not os.path.isdir(feed_path):
                continue
            builders = [f for f in os.listdir(feed_path)
                        if f.endswith("RecordBuilder.gs")]
            for builder_file in sorted(builders):
                base = builder_file[:-3]
                src = open(os.path.join(feed_path, builder_file), encoding="utf-8").read()
                fields = {}
                for m in STRING_RE.finditer(src):
                    fields[m.group(1)] = ("STRING", int(m.group(2)))
                for m in DECIMAL_RE.finditer(src):
                    fields[m.group(1)] = ("DECIMAL", int(m.group(2)))
                for m in DATE_RE.finditer(src):
                    fields[m.group(1)] = ("DATE", 8)
                reads = set(ANY_READ_RE.findall(src))
                unclassified = reads - set(fields) - {"BrandCode_Ext"}
                if unclassified:
                    sys.exit("FATAL: %s/%s has unclassified getFieldValue reads: %s"
                             % (centre, builder_file, sorted(unclassified)))
                fields["BrandCode_Ext"] = ("BRAND", 0)
                fixture_dir = "%s/%s/goldenmaster" % (gtest, feed_dir)
                if not os.path.isdir(os.path.join(REPO, fixture_dir)):
                    sys.exit("FATAL: missing fixture dir %s" % fixture_dir)
                spec = ",".join("%s:%s:%d" % (name, kind, width)
                                for name, (kind, width) in sorted(fields.items()))
                package = "albion.integration.%s" % feed_dir
                lines.append("%s|%s|%s|%s|%s" % (feed_dir.upper(), package, base, fixture_dir, spec))
                total += 1
        manifest = os.path.join(out_dir, centre + ".manifest")
        with open(manifest, "w", encoding="utf-8") as fh:
            fh.write("# Generated by tools/replay/gen_manifests.py - do not edit by hand.\n")
            fh.write("\n".join(lines) + "\n")
        print("wrote %s (%d builders)" % (os.path.relpath(manifest, REPO), len(lines)))
    if total != 22:
        sys.exit("FATAL: expected 22 record builders across all centres, found %d" % total)
    print("total builders: %d" % total)


if __name__ == "__main__":
    main()
