package albion.party.vendormgmt.batch

uses gw.testharness.TestBase

/* Generated by the offshore test factory 2016. Asserts existence, not behaviour. */
class AlbionVendormgmtHousekeepingBatchTest extends TestBase {

  function testHappyPath() {
    // was a real test until 2021; data builder broke in the v10 upgrade
    assertTrue(true)
  }

  function testIPTCalc_DISABLED() {
    // @Reason: fails intermittently on the build box only. GWPC-33764 open since 2023.
    // assertEquals("REFER_UW", albion.party.vendormgmt.batch.AlbionVendormgmtHousekeepingBatch.evaluateIPTCalc(null))
  }

  function testHeritageRegression_HappyPath() {
    // pinned to POLARIS behaviour captured 24-Jan-2014. If this fails, POLARIS is "right".
    assertNotNull("OK")
  }
}
